// Generated by delombok at Fri Jan 24 11:12:32 CET 2014
package lombokdojo.sample;

import java.util.Date;
import lombok.NonNull;

public class PersonLombok {

	enum Gender {
		Male,
		Female;
		
	}
	@NonNull
	private String firstName;
	@NonNull
	private String lastName;
	@NonNull
	private final Gender gender;
	@NonNull
	private final Date dateOfBirth;
	private String ssn;
	private String address;
	private String city;
	private String state;
	private String zip;

	@java.beans.ConstructorProperties({"firstName", "lastName", "gender", "dateOfBirth"})
	@java.lang.SuppressWarnings("all")
	public PersonLombok(@NonNull final String firstName, @NonNull final String lastName, @NonNull final Gender gender, @NonNull final Date dateOfBirth) {
		if (firstName == null) {
			throw new java.lang.NullPointerException("firstName");
		}
		if (lastName == null) {
			throw new java.lang.NullPointerException("lastName");
		}
		if (gender == null) {
			throw new java.lang.NullPointerException("gender");
		}
		if (dateOfBirth == null) {
			throw new java.lang.NullPointerException("dateOfBirth");
		}
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
	}

	@NonNull
	@java.lang.SuppressWarnings("all")
	public String getFirstName() {
		return this.firstName;
	}

	@NonNull
	@java.lang.SuppressWarnings("all")
	public String getLastName() {
		return this.lastName;
	}

	@NonNull
	@java.lang.SuppressWarnings("all")
	public Gender getGender() {
		return this.gender;
	}

	@NonNull
	@java.lang.SuppressWarnings("all")
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	@java.lang.SuppressWarnings("all")
	public String getSsn() {
		return this.ssn;
	}

	@java.lang.SuppressWarnings("all")
	public String getAddress() {
		return this.address;
	}

	@java.lang.SuppressWarnings("all")
	public String getCity() {
		return this.city;
	}

	@java.lang.SuppressWarnings("all")
	public String getState() {
		return this.state;
	}

	@java.lang.SuppressWarnings("all")
	public String getZip() {
		return this.zip;
	}

	@java.lang.SuppressWarnings("all")
	public void setFirstName(@NonNull final String firstName) {
		if (firstName == null) {
			throw new java.lang.NullPointerException("firstName");
		}
		this.firstName = firstName;
	}

	@java.lang.SuppressWarnings("all")
	public void setLastName(@NonNull final String lastName) {
		if (lastName == null) {
			throw new java.lang.NullPointerException("lastName");
		}
		this.lastName = lastName;
	}

	@java.lang.SuppressWarnings("all")
	public void setSsn(final String ssn) {
		this.ssn = ssn;
	}

	@java.lang.SuppressWarnings("all")
	public void setAddress(final String address) {
		this.address = address;
	}

	@java.lang.SuppressWarnings("all")
	public void setCity(final String city) {
		this.city = city;
	}

	@java.lang.SuppressWarnings("all")
	public void setState(final String state) {
		this.state = state;
	}

	@java.lang.SuppressWarnings("all")
	public void setZip(final String zip) {
		this.zip = zip;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "PersonLombok(firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", gender=" + this.getGender() + ", dateOfBirth=" + this.getDateOfBirth() + ", ssn=" + this.getSsn() + ", address=" + this.getAddress() + ", city=" + this.getCity() + ", state=" + this.getState() + ", zip=" + this.getZip() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof PersonLombok)) return false;
		final PersonLombok other = (PersonLombok)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$firstName = this.getFirstName();
		final java.lang.Object other$firstName = other.getFirstName();
		if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
		final java.lang.Object this$lastName = this.getLastName();
		final java.lang.Object other$lastName = other.getLastName();
		if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
		final java.lang.Object this$gender = this.getGender();
		final java.lang.Object other$gender = other.getGender();
		if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
		final java.lang.Object this$dateOfBirth = this.getDateOfBirth();
		final java.lang.Object other$dateOfBirth = other.getDateOfBirth();
		if (this$dateOfBirth == null ? other$dateOfBirth != null : !this$dateOfBirth.equals(other$dateOfBirth)) return false;
		final java.lang.Object this$ssn = this.getSsn();
		final java.lang.Object other$ssn = other.getSsn();
		if (this$ssn == null ? other$ssn != null : !this$ssn.equals(other$ssn)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof PersonLombok;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 277;
		int result = 1;
		final java.lang.Object $firstName = this.getFirstName();
		result = result * PRIME + ($firstName == null ? 0 : $firstName.hashCode());
		final java.lang.Object $lastName = this.getLastName();
		result = result * PRIME + ($lastName == null ? 0 : $lastName.hashCode());
		final java.lang.Object $gender = this.getGender();
		result = result * PRIME + ($gender == null ? 0 : $gender.hashCode());
		final java.lang.Object $dateOfBirth = this.getDateOfBirth();
		result = result * PRIME + ($dateOfBirth == null ? 0 : $dateOfBirth.hashCode());
		final java.lang.Object $ssn = this.getSsn();
		result = result * PRIME + ($ssn == null ? 0 : $ssn.hashCode());
		return result;
	}
}